---
# Material for MkDocs

services:
  mkdocs-material-evju:
    image: squidfunk/mkdocs-material
    container_name: mkdocs-material-evju
    restart: unless-stopped
    volumes:
      - .:/docs
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.mkdocs-material-evju.entrypoints=http
      - traefik.http.routers.mkdocs-material-evju.rule=Host(`docs.evju.info`)
      - traefik.http.middlewares.mkdocs-material-evju-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.mkdocs-material-evju.middlewares=mkdocs-material-evju-https-redirect
      - traefik.http.routers.mkdocs-material-evju-secure.entrypoints=https
      - traefik.http.routers.mkdocs-material-evju-secure.rule=Host(`docs.evju.info`)
      - traefik.http.routers.mkdocs-material-evju-secure.tls=true
      - traefik.http.routers.mkdocs-material-evju-secure.service=mkdocs-material-evju
      - traefik.http.services.mkdocs-material-evju.loadbalancer.server.port=8000
      - traefik.docker.network=proxy
      - com.centurylinklabs.watchtower.enable=true

networks:
    proxy:
        external: true
